In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
from env import RegionSensor
import os
import sys
sys.path.append(os.getcwd())

config = {
    'width':10,
    'height':10,
    'envs_img_folder_path':os.getcwd()+'/../demo_dmeirl/demo_label/train',
    'target_svf_delta':{50:0.5,40:1,30:1,20:1,10:1,0:1},
    'model_path':os.getcwd()+'/../demo_dmeirl/demo_result/1_model.pth',
    'max_step_count':20,
    'experts_traj_path':os.getcwd()+'/../demo_dmeirl/demo_expert_trajs_0205.csv',
}

region = RegionSensor(custom_config=config,config=None)


no background image


Get experts trajs num:500


parsing environments from folder:: 100%|██████████| 4/4 [00:00<00:00, 346.25it/s]


In [3]:
region.observation_space.sample()

array([[[1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 1, 0, 1, 0, 1],
        [1, 1, 0, 1, 1, 0, 0, 1, 1, 0],
        [1, 1, 0, 0, 0, 0, 1, 0, 1, 1],
        [1, 0, 0, 0, 1, 1, 1, 0, 0, 1],
        [0, 1, 1, 0, 0, 1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0, 0, 1, 1, 0, 1],
        [0, 1, 1, 1, 0, 1, 0, 1, 0, 0],
        [0, 1, 1, 1, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 1, 0, 1, 0, 1]],

       [[0, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        [1, 1, 0, 1, 1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 1, 0, 1, 0, 0],
        [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 0, 0, 1, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
        [1, 0, 0, 1, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0]],

       [[1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
        [0, 1, 0, 0, 1, 1, 1, 1, 0, 1],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 

In [4]:
region.step(60)

(array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
         [0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [

In [5]:
region.step(799)

(array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
         [0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [

In [14]:
region.observation_space.shape[0]

400

In [10]:
import gymnasium as gym
a = gym.spaces.Discrete(10)
a.sample()

7

In [11]:
env = gym.make('CartPole-v0').unwrapped

c:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\gymnasium\envs\registration.py:523: DeprecationWarning:

WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.



In [12]:
env.observation_space.shape[0]

4

In [7]:
region.observation_space.shape

(4, 10, 10)

In [ ]:
import math
def Least_common_multiple(num):  # 求任意多个数的最小公倍数
    minimum = 1
    for i in num:
        minimum = int(i)*int(minimum) / math.gcd(int(i), int(minimum))
    return int(minimum)

In [45]:
import torch
import torch.nn as nn
avg_pool = nn.AvgPool2d(kernel_size=(1,2),stride=(1,2))
x = torch.Tensor([[[1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6]],
                  [[1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6],
                   [1,2,3,4,5,6]]])
print(x.shape)
print(avg_pool(x))
x = avg_pool(x)
print(x.shape)

torch.Size([2, 5, 6])
tensor([[[1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000]],

        [[1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000],
         [1.5000, 3.5000, 5.5000]]])
torch.Size([2, 5, 3])
